### ISSUE TITLE
Add Landing UI

### ISSUE THREAD

**Issue by aiiiden** [catze-labs/jury-dao-web#5]
## Summary

- Nice Landing is required, there are some resources in public.

## TODO

- [x] Section 1 - Hero
- [x] Section 2 - Key Features
- [x] Section 3 - Fair Chance!
- [x] Section 4 - BIG HUGE CATCH
- [x] Section 5 - Team
- [x] Section 6 - FAQ
- [x] Section 7 - Join now!
